In [1]:
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in c:\users\hp\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\hp\anaconda3\lib\site-packages (from bs4) (4.9.3)
Requirement already satisfied: soupsieve>1.2; python_version >= "3.0" in c:\users\hp\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.0.1)
Requirement already satisfied: requests in c:\users\hp\anaconda3\lib\site-packages (2.24.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\hp\anaconda3\lib\site-packages (from requests) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests) (1.25.11)

In [2]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re

# Q1. Scrape the details of most viewed videos on YouTube from Wikipedia

In [5]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(4)

url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)
time.sleep(6)

#creating empty lists
name=[]
artist=[]
upload_date = []
views=[]


#scraping names of the video



try:

    names=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")

    for i in names:

        name.append(i.text)

except NoSuchElementException:#handling no such element exception

    name.append('No details available')

except StaleElementReferenceException:#handling Stale element exception

    name.append('No details available')
    
time.sleep(4)
    
    
#scraping names of the artist
    
try:

    artist_names = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")

    for i in artist_names:

        artist.append(i.text)

except NoSuchElementException:#handling no such element exception

    name.append('No details available')

except StaleElementReferenceException:#handling Stale element exception

    name.append('No details available')
    
time.sleep(4)
    
#scraping date of uploading the video
try:

    date = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")

    for i in date:

        upload_date.append(i.text)

except NoSuchElementException:#handling no such element exception

    upload_date.append('No details available')

except StaleElementReferenceException:#handling Stale element exception

    upload_date.append('No details available')
    
#scraping the data of number of views in billions


try:

    view = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")

    for i in view:

        views.append(i.text)

except NoSuchElementException:#handling no such element exception

    views.append('No details available')

except StaleElementReferenceException:#handling Stale element exception

    views.append('No details available')

        

time.sleep(4)

 # creating the dataframe 
df=pd.DataFrame({"Rank": range(0,30), "Name of the video":name,"Name of the artist":artist,"Upload date":upload_date,
                 "Views(in billions)":views})
df

,Rank,Name of the video,Name of the artist,Upload date,Views(in billions)
0,0,"""Baby Shark Dance""[23]",Pinkfong Kids' Songs & Stories,"June 17, 2016",9.27
1,1,"""Despacito""[25]",Luis Fonsi,"January 12, 2017",7.52
2,2,"""Johny Johny Yes Papa""[26]",LooLoo Kids,"October 8, 2016",5.68
3,3,"""Shape of You""[27]",Ed Sheeran,"January 30, 2017",5.45
4,4,"""See You Again""[28]",Wiz Khalifa,"April 6, 2015",5.25
5,5,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,"May 2, 2018",4.49
6,6,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,"February 27, 2018",4.46
7,7,"""Masha and the Bear – Recipe for Disaster""[33]",Get Movies,"January 31, 2012",4.46
8,8,"""Uptown Funk""[34]",Mark Ronson,"November 19, 2014",4.28
9,9,"""Gangnam Style""[35]",Psy,"July 15, 2012",4.18
10,10,"""Phonics Song with Two Words""[37]",ChuChu TV,"March 6, 2014",4.14
11,11,"""Dame Tu Cosita""[38]",El Chombo,"April 5, 2018",3.57
12,12,"""Sugar""[39]",Maroon 5,"January 14, 2015",3.54
13,13,"""Sorry""[40]",Justin Bieber,"October 22, 2015",3.46
14,14,"""Roar""[41]",Katy Perry,"September 5, 2013",3.42
15,15,"""Counting Stars""[42]",OneRepublic,"May 31, 2013",3.38
16,16,"""Thinking Out Loud""[43]",Ed Sheeran,"October 7, 2014",3.31
17,17,"""Wheels on the Bus""[44]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.24
18,18,"""Dark Horse""[45]",Katy Perry,"February 20, 2014",3.14
19,19,"""Faded""[46]",Alan Walker,"December 3, 2015",3.13
20,20,"""Girls Like You""[47]",Maroon 5,"May 31, 2018",3.11
21,21,"""Shake It Off""[48]",Taylor Swift,"August 18, 2014",3.09
22,22,"""Lean On""[49]",Major Lazer,"March 22, 2015",3.09
23,23,"""Bailando""[50]",Enrique Iglesias,"April 11, 2014",3.09
24,24,"""Let Her Go""[51]",Passenger,"July 25, 2012",3.07
25,25,"""Axel F""[52]",Crazy Frog,"June 16, 2009",2.98
26,26,"""Mi Gente""[53]",J Balvin,"June 29, 2017",2.97
27,27,"""Perfect""[54]",Ed Sheeran,"November 9, 2017",2.94
28,28,"""Waka Waka (This Time for Africa)""[55]",Shakira,"June 4, 2010",2.93
29,29,"""Hello""[56]",Adele,"October 22, 2015",2.88

In [6]:
driver.close()

# Q2 Scrape the details team India’s international fixtures from bcci.tv

In [8]:
driver=webdriver.Chrome("chromedriver.exe") 

url = "https://www.bcci.tv/"
driver.get(url)


#going to international fixtures page
from selenium.common.exceptions import ElementNotInteractableException

fixtures=driver.find_element_by_xpath("//div[@class='navigation__drop-down drop-down drop-down--reveal-on-hover']/div/ul/li/a")

try:

    fixtures.click()

except ElementNotInteractableException:

    driver.get(fixtures.get_attribute('href'))
    
#creating empty lists
Match_title = []
Series = []
Place = []
Date = []
Time = []

In [9]:
#scraping match title


try:

    title = driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")

    for i in title:

        Match_title.append(i.text)

except NoSuchElementException:#handling no such element exception

    Match_title.append('No details available')

except StaleElementReferenceException:#handling Stale element exception

    Match_title.append('No details available')
    


    
#scraping series
    
try:

    ser = driver.find_elements_by_xpath("//span[@class='u-unskewed-text fixture__tournament-label u-truncated']")

    for i in ser:

        Series.append(i.text)

except NoSuchElementException:#handling no such element exception

    Series.append('No details available')

except StaleElementReferenceException:#handling Stale element exception

    Series.append('No details available')
    

    
#scraping place
try:

    pl = driver.find_elements_by_xpath("//p[@class='fixture__additional-info'][1]/span")

    for i in pl:

        Place.append(i.text)

except NoSuchElementException:#handling no such element exception

    Place.append('No details available')

except StaleElementReferenceException:#handling Stale element exception

    Place.append('No details available')
    
Place
    

#scraping date


try:

    date =driver.find_elements_by_xpath("//div[@class='fixture__datetime desktop-only']/div/span")
    month=driver.find_elements_by_xpath("//div[@class='fixture__datetime desktop-only']/div/div/span[1]")
    j=len(date)
    for i in range(j):
        try:
            Date.append(date[i].text+" "+month[i].text)
        except:
            Date.append("-") 
    

except NoSuchElementException:#handling no such element exception

    Date.append('No details available')

except StaleElementReferenceException:#handling Stale element exception

    Date.append('No details available')

                                
#scraping time

try:

    time = driver.find_elements_by_xpath("//span[@class='fixture__time']")

    for i in time:

        Time.append(i.text)

except NoSuchElementException:#handling no such element exception

    Time.append('No details available')

except StaleElementReferenceException:#handling Stale element exception

    Time.append('No details available')

        
 # creating the dataframe 
df=pd.DataFrame({"Match Title":Match_title, "Series":Series,"Place":Place, "Time":Time,"Date":Date})
df

,Match Title,Series,Place,Time,Date
0,5th Test,ENGLAND V INDIA 2021,"Old Trafford, Manchester",15:30 IST,10 SEPTEMBER
1,Match 16,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",19:30 IST,24 OCTOBER
2,Match 28,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",19:30 IST,31 OCTOBER
3,Match 33,2021 ICC MEN'S T20 WORLD CUP,"Sheikh Zayed Cricket Stadium, Abu Dhabi",19:30 IST,03 NOVEMBER
4,Match 37,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",19:30 IST,05 NOVEMBER
5,Match 42,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",19:30 IST,08 NOVEMBER

In [10]:
driver.close()    #closing the driver

# Q3 Scrape the details of selenium exception from guru99.com.

In [11]:
#connecting to the web driver and opening the url
driver=webdriver.Chrome("chromedriver.exe") 

url = "https://www.guru99.com"
driver.get(url)

#clicking element for selenium
s1 = driver.find_element_by_xpath("//div[@class='srch']/span[8]/a") 
s1.click

#clicking selenium exception handling tutorial
s2 = driver.find_element_by_xpath("//span[@class='srch-icon hidden-phone'][4]/a")
s2.click()

#opening the tutorial
s3 = driver.find_element_by_xpath("//table[@class='table']/tbody/tr[34]/td/a")
s3.click()

#creating empty list
NAME = []
DESCRIPTION = []

#extracting names

name = driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")

for i in name:
    try:
        NAME.append(i.text)
    except:
        NAME.append('-')
        

#extracting description

des = driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")

for i in des:
    try:
        DESCRIPTION.append(i.text)
    except:
        DESCRIPTION.append('-')
        

#Creating the dataframe

excep_handling = pd.DataFrame({})
excep_handling['NAME OF THE EXCEPTION'] = NAME
excep_handling['DESCRIPTION'] = DESCRIPTION
excep_handling

,NAME OF THE EXCEPTION,DESCRIPTION
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [12]:
#close the driver
driver.close()

# Q4. Scrape the details of State-wise GDP of India from statisticstime.com

In [13]:
#connecting to the web driver and opening the url

driver=webdriver.Chrome("chromedriver.exe") 

url = "http://statisticstimes.com/"
driver.get(url)

#opening the economy tab

economy = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/button")
economy.click()


#clicking the india tab

india = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/div/a[3]")
india.click()

In [14]:
#clicking the state wise GDP of India

GDP = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
GDP.click()


#creating empty lists

Rank = []
State = []
GSDP_20 = []
GSDP_19 = []
Share_19 = []
GDP_Billion = []

In [15]:
#extracting names

n = driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[1]")

for i in n:
    try:
        Rank.append(i.text)
    except:
        Rank.append("-")

        
#extracting state list

s = driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[2]")
for i in s:
    try:
        State.append(i.text)
    except:
        State.append("-")

        
#extracting GSDP(19-20)

gdp = driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[3]")
for i in gdp:
    try:
        GSDP_20.append(i.text)
    except:
        GSDP_20.append("-")

        
#extracting GSDP(18-19)

gdp_ = driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[4]")
for i in gdp_:
    try:
        GSDP_19.append(i.text)
    except:
        GSDP_19.append("-")
        

#extracting share(18-19)

share = driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[5]")
for i in share:
    try:
        Share_19.append(i.text)
    except:
        Share_19.append("-")

        
#extracting GDP(in $ billions)

gdp_1 = driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[6]")
for i in gdp_1:
    try:
        GDP_Billion.append(i.text)
    except:
        GDP_Billion.append("-")

        
#creating the datadrame

State_GDP = pd.DataFrame({})
State_GDP['RANK'] = Rank[0:297]
State_GDP['STATE'] = State[0:297]
State_GDP['GSDP at current price(19-20)'] = GSDP_20[0:297]
State_GDP['GSDP at current price(18-19)'] = GSDP_19[0:297]
State_GDP['Share(18-19)'] = Share_19[0:297]
State_GDP['GDP($ billion)'] = GDP_Billion[0:297]
State_GDP

,RANK,STATE,GSDP at current price(19-20),GSDP at current price(18-19),Share(18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [16]:
driver.close()

# Q5. Scrape the details of trending repositories on Github.com.

In [18]:
#connecting to the web driver and opening the url

driver=webdriver.Chrome("chromedriver.exe") 

url = "https://github.com/"
driver.get(url)

In [19]:
#clicking the explore tab

l = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")

l.click()

#clicking the trending tab

trending = driver.find_element_by_xpath("//ul[@class='list-style-none mb-3']/li[3]/a")
trending.click()

In [20]:
#creating empty lists

Repository_title = []
Repository_description = []
Contributors_count = []
Language_used = []
url = []

In [21]:
#extracting Repository title

rep = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
for i in rep:
    try:
        Repository_title.append(i.text)
    except:
        Repository_title.append("-")
        
#Extracting Contributors_countlist
rep1 = driver.find_elements_by_xpath("//*[@id='js-pjax-container']/div[3]/div/div[2]/article/div[2]/a[2]")
for i in rep1:
    try:
        Contributors_count.append(i.text)
    except:
        Contributors_count.append("-")

        
# urls for Repository_desc & Language_usedinfo
link = driver.find_elements_by_xpath("//article[@class='Box-row']/h1/a")
for i in link:
    url.append(i.get_attribute("href"))

    

#Extracting Repository description
for i in url:
    driver.get(i)
    try:
        rep1=driver.find_element_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]/div/div[1]/div/p | //*[@id="repo-content-pjax-container"]/div/div[2]/div[2]/div/div[1]/div/div[1]')
        Repository_description.append(rep1.text)
    except NoSuchElementException as e:
            Repository_description.append("-")
            
            
#Extracting Language_used 
for i in url:
    driver.get(i)
    try:
        rep3=driver.find_element_by_xpath('//span[@class="color-text-primary text-bold mr-1"]')
        Language_used.append(rep3.text)
    except NoSuchElementException as e:
            Language_used.append("-")  

            

#creating the dataframe
Github=pd.DataFrame({})
Github['Repository Title']=Repository_title[0:25]
Github['Repository Description']=Repository_description[0:25]
Github['Contributors Count']=Contributors_count[0:25]
Github['Language Used']=Language_used[0:25]
Github

,Repository Title,Repository Description,Contributors Count,Language Used
0,GTAmodding / re3,"GTA III, Vice City",802,C++
1,VickScarlet / lifeRestart,やり直すんだ。そして、次はうまくやる。,"1,152",JavaScript
2,lootproject / website,Loot Project website,85,TypeScript
3,TheAlgorithms / Python,All Algorithms implemented in Python,"31,424",Python
4,Anish-Agnihotri / dhof-loot,Scripts to collect statistics about LOOT + der...,51,JavaScript
5,TheAlgorithms / C-Plus-Plus,Collection of various algorithms in mathematic...,"4,069",C++
6,donnemartin / system-design-primer,Learn how to design large-scale systems. Prep ...,"26,379",Python
7,microsoft / PowerToys,Windows system utilities to maximize productivity,"3,282",C#
8,openwrt / openwrt,This repository is a mirror of https://git.ope...,"6,169",C
9,v2fly / v2ray-core,A platform for building proxies to bypass netw...,"1,890",Go
10,MarlinFirmware / Marlin,Marlin is an optimized firmware for RepRap 3D ...,"14,933",C++
11,HashLips / generative-art-opensource,Create generative art by using the canvas api ...,117,JavaScript
12,vxunderground / MalwareSourceCode,Collection of malware source code for a variet...,708,Assembly
13,metaplex-foundation / metaplex,Protocol and application framework for decentr...,"1,288",Rust
14,armosec / kubescape,kubescape is the first tool for testing if Kub...,105,Go
15,wrfree / free,freefq账号已恢复！翻墙、免费翻墙、免费科学上网、免费节点、免费梯子、免费ss/v2ra...,33,-
16,bespoyasov / frontend-clean-architecture,React + TypeScript app built using clean archi...,37,TypeScript
17,TheAlgorithms / Javascript,A repository for All algorithms implemented in...,"2,348",JavaScript
18,0voice / Introduction-to-Golang,【未来服务器端编程语言】最全空降golang资料补给包（满血战斗），包含文章，书籍，作者论文...,430,-
19,iptv-org / iptv,Collection of publicly available IPTV channels...,"3,195",JavaScript
20,Anuken / Mindustry,A sandbox tower defense game,"1,666",Java
21,30-seconds / 30-seconds-of-code,Short JavaScript code snippets for all your de...,"8,912",JavaScript
22,NotLuksus / nft-art-generator,A tool to generate generative NFT art projects.,67,JavaScript
23,vnpy / vnpy,基于Python的开源量化交易平台开发框架,"6,581",C++
24,jackfrued / Python-100-Days,Python - 100天从新手到大师,"42,638",Python

In [22]:
#closing the driver
driver.close()

# Q6. Scrape the details of top 100 songs on billboard.com

In [23]:
#connecting to the web driver and opening the url

driver=webdriver.Chrome("chromedriver.exe") 

url="https://www.billboard.com/"
driver.get(url)

In [24]:
#clicking charts option
chart = driver.find_element_by_xpath("//*[@id='root']/div[2]/div[2]/header/div/ul/li[1]/a")
chart.click()

In [26]:
#clicking top 100 songs

top_100 = driver.find_element_by_xpath("//*[@id='main']/div[2]/div/div[1]/a/div[2]/div[2]/div[1]")
top_100.click()

In [27]:
#Creating empty Lists
Song_name=[]
Artist_name=[]
Lastweek_rank=[]
Peak_rank=[]
Weeks_on_board=[]

In [35]:
#Extracting Song_name
song = driver.find_elements_by_xpath("//*[@id='charts']/div/div[7]/div/ol/li/button/span[2]/span[1]")
for i in song:
    try:
        Song_name.append(i.text)
    except:
        Song_name.append("-")

#Extracting Artist_name
artist = driver.find_elements_by_xpath("//*[@id='charts']/div/div[7]/div/ol/li/button/span[2]/span[2]")
for i in artist:
    try:
        Artist_name.append(i.text)
    except:
        Artist_name.append("-")
        
#Extracting Lastweek_rank
rank = driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--last']")
for i in rank:
    try:
        Lastweek_rank.append(i.text)
    except:
        Lastweek_rank.append("-")
        
#Extracting Peak_rank
peak_rank=driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--peak']")
for i in peak_rank:
    try:
        Peak_rank.append(i.text)
    except:
        Peak_rank.append("-")


#Extracting Weeks_on_board
onboard = driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
for i in onboard:
    try:
        Weeks_on_board.append(i.text)
    except:
        Weeks_on_board.append("-")


#creating the dataframe

hot100=pd.DataFrame({})
hot100['Song Name']=Song_name[0:100]
hot100['Artist Name']=Artist_name[0:100]
hot100['Last Week Rank']=Lastweek_rank[0:100]
hot100['Peak Rank']=Peak_rank[0:100]
hot100['Weeks Onboard']=Weeks_on_board[0:100]
hot100

,Song Name,Artist Name,Last Week Rank,Peak Rank,Weeks Onboard
0,Stay,The Kid LAROI & Justin Bieber,1,1,7
1,Bad Habits,Ed Sheeran,2,2,9
2,Good 4 U,Olivia Rodrigo,3,1,15
3,Kiss Me More,Doja Cat Featuring SZA,5,3,20
4,Industry Baby,Lil Nas X & Jack Harlow,7,2,5
...,...,...,...,...,...
95,Tick Tock,Young Thug,-,96,1
96,Permission To Dance,BTS,66,1,7
97,AM,Nio Garcia X J Balvin X Bad Bunny,85,41,9
98,Time Heals,Rod Wave,-,99,1
99,Thinking 'Bout You,Dustin Lynch Featuring Lauren Alaina Or MacKen...,91,91,2

In [36]:
#closing the driver

driver.close()

# Q7. Scrape the details of Data science recruiters from naukri.com.

In [37]:
#connecting to the web driver and opening the url

driver=webdriver.Chrome("chromedriver.exe") 

url="https://www.naukri.com/"
driver.get(url)

In [38]:
#recruitment

r = driver.find_element_by_xpath("//*[@id='root']/div[1]/div/ul[1]/li[2]/a")
driver.get(r.get_attribute('href'))

In [39]:
#searching Data Science jobs

s = driver.find_element_by_xpath("//*[@id='skill']/div[1]/div[2]/input")
s.send_keys('Data Science')

In [41]:
#clicking the search button

btn = driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']")
btn.click()

In [42]:
#creating empty lists

Name = []
Designation = []
Company = []
Skills = []
Location = []

In [50]:
#Extracting name
name = driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[1]")
for i in name:
    try:
        Name.append(i.text)
    except:
        Name.append("-")

#Extracting Designation
des = driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[1]")
for i in des:
    try:
        Designation.append(i.text)
    except:
        Designation.append("-")
        
#Extracting Company
comp = driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[2]")
for i in comp:
    try:
        Company.append(i.text)
    except:
        Company.append("-")
Company

#Extracting Skills
skill = driver.find_elements_by_xpath("//div[@class='recInfo']/div[2]")
for i in skill:
    try:
        Skills.append(i.text)
    except:
        Skills.append("-")

 #Extracting Location
soup = BeautifulSoup(driver.page_source,'html.parser')
locate = soup.find_all('div',attrs={'vcard'})
for i in locate:
    try:
        Location.append(i.find('small').text)
    except AttributeError :
        Location.append("No Location available")
        
        
#creating the dataframe

jobs = pd.DataFrame({})
jobs['Recruiter Name'] = Name[0:100]
jobs['Designation'] = Designation[0:100]
jobs['Company'] = Company[0:100]
jobs['Skills they hire for'] = Skills[0:100]
jobs['Location'] = Location[0:100]
jobs

,Recruiter Name,Designation,Company,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
...,...,...,...,...,...
95,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
96,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
97,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
98,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
99,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",No Location available

In [51]:
driver.close()

# Q8. . Scrape the details of Highest selling novels.

In [68]:
#connecting to the web driver and opening the url

driver=webdriver.Chrome("chromedriver.exe") 

url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)

In [69]:
#creating empty lists

Book_name=[]
Author_name=[]
Volumes_sold=[]
Publisher = []
Genre = []

In [70]:
#Extracting Book name
b = driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[2]")
for i in b :
    try:
        Book_name.append(i.text)
    except:
        Book_name.append("-")
        
#Extracting Author name
a = driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[3]")
for i in a:
    try:
        Author_name.append(i.text)
    except:
        Author_name.append("-")
        
#Extracting Volumes sold
v = driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[4]")
for i in v:
    try:
        Volumes_sold.append(i.text)
    except:
        Volumes_sold.append("-")
        
#Extracting Publisher_info
p = driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[5]")
for i in p:
    try:
        Publisher.append(i.text)
    except:
        Publisher.append("-")

#Extracting information for Genre_info
g = driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[6]")
for i in g:
    try:
        Genre.append(i.text)
    except:
        Genre.append("-")


#creating the dataframe
top_novels = pd.DataFrame({})
top_novels['Book Name'] = Book_name[0:200]
top_novels['Author Name'] = Author_name[0:200]
top_novels['Volumes Sold'] = Volumes_sold[0:200]
top_novels['Publisher Info'] = Publisher[0:200]
top_novels['Genre Info'] = Genre[0:200]
top_novels

,Book Name,Author Name,Volumes Sold,Publisher Info,Genre Info
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [71]:
#closing the driver
driver.close()

# Q9. . Scrape the details most watched tv series of all time from imdb.com

In [72]:
#connecting to the web driver and opening the url

driver=webdriver.Chrome("chromedriver.exe") 

url = "https://www.imdb.com/list/ls095964455/"
driver.get(url)

In [74]:
#creating the empty list

Name = []
YearSpan = []
Genre = []
RunTime = []
Ratings = []
Votes = []

In [75]:
#Extracting TvSeries_Name
t = driver.find_elements_by_xpath("//*[@id='main']/div/div[3]/div[3]/div/div[2]/h3/a")
for i in t:
    try:
        Name.append(i.text)
    except:
        Name.append("-")
        
#Extracting TvSeries_YearSpan
span = driver.find_elements_by_xpath("//*[@id='main']/div/div[3]/div[3]/div/div[2]/h3/span[2]")
for i in span:
    try:
        YearSpan.append(i.text)
    except:
        YearSpan.append("-")
        
#Extracting TvSeries_Genre
genre = driver.find_elements_by_xpath("//*[@id='main']/div/div[3]/div[3]/div/div[2]/p[1]/span[5]")
for i in genre:
    try:
        Genre.append(i.text)
    except:
        Genre.append("-")
        

#Extracting TvSeries_RunTime
runtime = driver.find_elements_by_xpath("//*[@id='main']/div/div[3]/div[3]/div/div[2]/p[1]/span[3]")
for i in runtime:
    try:
        RunTime.append(i.text)
    except:
        RunTime.append("-")
        
#Extracting TvSeries_Ratings
ratings = driver.find_elements_by_xpath("//*[@id='main']/div/div[3]/div[3]/div/div[2]/div[1]/div[1]/span[2]")
for i in ratings:
    try:
        Ratings.append(i.text)
    except:
        Ratings.append("-")
        
#Extracting TvSeries_Votes
votes = driver.find_elements_by_xpath("//*[@id='main']/div/div[3]/div[3]/div/div[2]/p[4]/span[2]")
for i in votes:
    try:
        Votes.append(i.text)
    except:
        Votes.append("-")
        

#creating the dataframe
TvSeries = pd.DataFrame({})
TvSeries['TvSeries Name'] = Name
TvSeries['Year Span'] = YearSpan
TvSeries['Genre'] = Genre
TvSeries['RunTime'] = RunTime
TvSeries['Ratings'] = Ratings
TvSeries['Votes'] = Votes
TvSeries

,TvSeries Name,Year Span,Genre,RunTime,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,867,559"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"903,132"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"894,609"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"269,246"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"229,513"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,485"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"56,357"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8,"174,373"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"36,488"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"198,214"

In [76]:
#closing the driver
driver.close()

# Q10. . Details of Datasets from UCI machine learning repositories

In [77]:
#connecting to the web driver and opening the url

driver=webdriver.Chrome("chromedriver.exe") 

url = "https://archive.ics.uci.edu/"
driver.get(url)

In [78]:
#clicking dataset link

ds = driver.find_element_by_xpath("/html/body/table[1]/tbody/tr/td[2]/span[2]/a/font/b")
ds.click()

In [79]:
#creating the empty list

Dataset_Name=[]
Data_type=[]
Task=[]
Attribute_type=[]
No_of_instances=[]
No_of_attribute=[]
Year=[]

In [83]:
#Extracting Dataset_Name
d = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
for i in d:
    try:
        Dataset_Name.append(i.text)
    except:
        Dataset_Name.append("-")
        

#Extracting Data_type
dtype = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
for i in dtype[1:]:
    try:
        Data_type.append(i.text)
    except:
        Data_type.append("-")
        
#Extracting Task
task = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]/p")
for i in task[1:]:
    try:
        Task.append(i.text)
    except:
        Task.append("-")
        

#Extracting Attribute_type
att = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]/p")
for i in att[1:]:
    try:
        Attribute_type.append(i.text)
    except:
        Attribute_type.append("-")    
        
#Extracting Number of instances
instances = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]/p")
for i in instances[1:]:
    try:
        No_of_instances.append(i.text)
    except:
        No_of_instances.append("-")

#Extracting Number of attribute
attr = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]/p")
for i in attr[1:]:
    try:
        No_of_attribute.append(i.text)
    except:
        No_of_attribute.append("-")
        
#Extracting Year
year = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]/p")
for i in year[1:]:
    try:
        Year.append(i.text)
    except:
        Year.append("-")
        

#creating dataframe
dataset = pd.DataFrame({})
dataset['Dataset Name' ] = Dataset_Name[0:1763]
dataset['Data type'] = Data_type[0:1763]
dataset['Task'] = Task[0:1763]
dataset['Attribute type'] = Attribute_type[0:1763]
dataset['No of instances'] = No_of_instances[0:1763]
dataset['No of attribute'] = No_of_attribute[0:1763]
dataset['Year'] = Year[0:1763]
dataset

,Dataset Name,Data type,Task,Attribute type,No of instances,No of attribute,Year
0,Abalone,Data Types,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,Multivariate,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
1758,in-vehicle coupon recommendation,"Multivariate, Time-Series",Classification,"Integer, Real",13611,17,2020
1759,Gait Classification,Multivariate,Classification,,12684,23,2020
1760,Wikipedia Math Essentials,Multivariate,Classification,Real,48,321,2020
1761,Wikipedia Math Essentials,Multivariate,Regression,Real,731,1068,2021
1762,Synchronous Machine Data Set,Time-Series,Regression,Real,731,1068,2021

In [84]:
#closing the driver
driver.close()